//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.2+g858356d409
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 2.4 -InputFile circles-menu-1.json
//       
//       Input file:
//           circles-menu-1.json (9084 bytes created 12:57+01:00 Feb 4 2024)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ___________________________________________________________
// |       Object stats       | UAP v15 count | UAP v7 count |
// |__________________________|_______________|______________|
// | All CompositionObjects   |            84 |          112 |
// |--------------------------+---------------+--------------|
// | Expression animators     |             1 |           15 |
// | KeyFrame animators       |            15 |           15 |
// | Reference parameters     |             1 |           15 |
// | Expression operations    |             0 |            0 |
// |--------------------------+---------------+--------------|
// | Animated brushes         |             - |            - |
// | Animated gradient stops  |             - |            - |
// | ExpressionAnimations     |             1 |            1 |
// | PathKeyFrameAnimations   |             - |            - |
// |--------------------------+---------------+--------------|
// | ContainerVisuals         |             1 |            1 |
// | ShapeVisuals             |             1 |            1 |
// |--------------------------+---------------+--------------|
// | ContainerShapes          |            11 |           11 |
// | CompositionSpriteShapes  |             6 |            6 |
// |--------------------------+---------------+--------------|
// | Brushes                  |             2 |            2 |
// | Gradient stops           |             - |            - |
// | CompositionVisualSurface |             - |            - |
// -----------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    // Name:        circles-menu-1
    // Frame rate:  24 fps
    // Frame count: 28
    // Duration:    1166.7 mS
    sealed class Circles_menu_1
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        // Animation duration: 1.167 seconds.
        internal const long c_durationTicks = 11666666;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (Circles_menu_1_AnimatedVisual_UAPv15.IsRuntimeCompatible())
            {
                var res = 
                    new Circles_menu_1_AnimatedVisual_UAPv15(
                        compositor
                        );
                    return res;
            }

            if (Circles_menu_1_AnimatedVisual_UAPv7.IsRuntimeCompatible())
            {
                var res = 
                    new Circles_menu_1_AnimatedVisual_UAPv7(
                        compositor
                        );
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 28d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 24d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(11666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 28d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Circles_menu_1_AnimatedVisual_UAPv15 : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 11666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostSkyBlue_FF8BB7F0;
            CompositionColorBrush _colorBrush_AlmostSteelBlue_FF4E7AB5;
            CompositionPathGeometry _pathGeometry;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            ScalarKeyFrameAnimation _scalarAnimation_0p2_to_0p6;
            ScalarKeyFrameAnimation _scalarAnimation_0p6_to_0p2;
            ScalarKeyFrameAnimation _scalarAnimation_1_to_1_0;
            ScalarKeyFrameAnimation _scalarAnimation_1_to_1_1;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(result, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -3.5F));
                    builder.AddCubicBezier(new Vector2(-1.93299997F, -3.5F), new Vector2(-3.5F, -1.93299997F), new Vector2(-3.5F, 0F));
                    builder.AddCubicBezier(new Vector2(-3.5F, 1.93299997F), new Vector2(-1.93299997F, 3.5F), new Vector2(0F, 3.5F));
                    builder.AddCubicBezier(new Vector2(1.93299997F, 3.5F), new Vector2(3.5F, 1.93299997F), new Vector2(3.5F, 0F));
                    builder.AddCubicBezier(new Vector2(3.5F, -1.93299997F), new Vector2(1.93299997F, -3.5F), new Vector2(0F, -3.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostSkyBlue_FF8BB7F0()
            {
                return _colorBrush_AlmostSkyBlue_FF8BB7F0 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x8B, 0xB7, 0xF0));
            }

            CompositionColorBrush ColorBrush_AlmostSteelBlue_FF4E7AB5()
            {
                return _colorBrush_AlmostSteelBlue_FF4E7AB5 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x4E, 0x7A, 0xB5));
            }

            // Layer aggregator
            // Layer: Circle 1
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(ContainerShape_01());
                result.StartAnimation("Scale", ShapeVisibilityAnimation_0(), _animationController_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 1
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(5F, 20F);
                // ShapeGroup: Group 2 Offset:<5, 20>
                result.Shapes.Add(SpriteShape_0());
                result.StartAnimation("Scale", ScaleVector2Animation_0(), AnimationController_0());
                return result;
            }

            // Layer aggregator
            // Layer: Circle 4
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_03());
                result.StartAnimation("Scale", ShapeVisibilityAnimation_1(), _animationController_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 4
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(5F, 20F);
                // ShapeGroup: Group 2 Offset:<5, 20>
                result.Shapes.Add(SpriteShape_1());
                result.StartAnimation("Scale.X", ScalarAnimation_0p2_to_0p6(), _animationController_0);
                result.StartAnimation("Scale.Y", _scalarAnimation_0p2_to_0p6, _animationController_0);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 2
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(ContainerShape_05());
                result.StartAnimation("Scale", ShapeVisibilityAnimation_2(), _animationController_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 2
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(20F, 20F);
                // ShapeGroup: Group 1 Offset:<20, 20>
                result.Shapes.Add(SpriteShape_2());
                result.StartAnimation("Scale.X", ScalarAnimation_1_to_1_0(), _animationController_0);
                result.StartAnimation("Scale.Y", _scalarAnimation_1_to_1_0, _animationController_0);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 5
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_07());
                result.StartAnimation("Scale", ShapeVisibilityAnimation_3(), _animationController_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 5
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(20F, 20F);
                // ShapeGroup: Group 1 Offset:<20, 20>
                result.Shapes.Add(SpriteShape_3());
                result.StartAnimation("Scale.X", ScalarAnimation_1_to_1_1(), _animationController_0);
                result.StartAnimation("Scale.Y", _scalarAnimation_1_to_1_1, _animationController_0);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(35F, 20F);
                // ShapeGroup: Group 3 Offset:<35, 20>
                result.Shapes.Add(SpriteShape_4());
                result.StartAnimation("Scale.X", ScalarAnimation_0p6_to_0p2(), _animationController_0);
                result.StartAnimation("Scale.Y", _scalarAnimation_0p6_to_0p2, _animationController_0);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 6
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_10());
                result.StartAnimation("Scale", ShapeVisibilityAnimation_4(), _animationController_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 6
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(35F, 20F);
                // ShapeGroup: Group 3 Offset:<35, 20>
                result.Shapes.Add(SpriteShape_5());
                result.StartAnimation("Scale", ScaleVector2Animation_1(), _animationController_0);
                return result;
            }

            CompositionPathGeometry PathGeometry()
            {
                return _pathGeometry = _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // - - Layer aggregator
            // - Layer: Circle 1
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<5, 20>
                var geometry = PathGeometry();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 5F, 20F), ColorBrush_AlmostSkyBlue_FF8BB7F0());;
                result.StrokeBrush = ColorBrush_AlmostSteelBlue_FF4E7AB5();
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 4
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<5, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 5F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 2
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<20, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 5
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<20, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<35, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 35F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 6
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<35, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 35F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.550000012F, 1F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.444000006F, 0F), new Vector2(0.833000004F, 0.833000004F));
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p2_to_0p6()
            {
                // Frame 0.
                var result = _scalarAnimation_0p2_to_0p6 = CreateScalarKeyFrameAnimation(0F, 0.200000003F, StepThenHoldEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, 0.200000003F, _holdThenStepEasingFunction);
                // Frame 19.
                result.InsertKeyFrame(0.678571403F, 1F, CubicBezierEasingFunction_1());
                // Frame 28.
                result.InsertKeyFrame(1F, 0.600000024F, CubicBezierEasingFunction_2());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p6_to_0p2()
            {
                // Frame 0.
                var result = _scalarAnimation_0p6_to_0p2 = CreateScalarKeyFrameAnimation(0F, 0.600000024F, _holdThenStepEasingFunction);
                // Frame 8.
                result.InsertKeyFrame(0.285714298F, 1F, _cubicBezierEasingFunction_1);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, 0.200000003F, _cubicBezierEasingFunction_2);
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_1_to_1_0()
            {
                // Frame 0.
                var result = _scalarAnimation_1_to_1_0 = CreateScalarKeyFrameAnimation(0F, 1F, _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, 0.200000003F, _cubicBezierEasingFunction_2);
                // Frame 28.
                result.InsertKeyFrame(1F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.550000012F, 1F)));
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_1_to_1_1()
            {
                // Frame 0.
                var result = _scalarAnimation_1_to_1_1 = CreateScalarKeyFrameAnimation(0F, 1F, _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, 0.200000003F, _c.CreateCubicBezierEasingFunction(new Vector2(0.444000006F, 0F), new Vector2(0.833000004F, 1F)));
                // Frame 28.
                result.InsertKeyFrame(1F, 1F, _cubicBezierEasingFunction_1);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(40F, 40F);
                var shapes = result.Shapes;
                // Layer: Circle 1
                shapes.Add(ContainerShape_00());
                // Layer: Circle 4
                shapes.Add(ContainerShape_02());
                // Layer: Circle 2
                shapes.Add(ContainerShape_04());
                // Layer: Circle 5
                shapes.Add(ContainerShape_06());
                shapes.Add(ContainerShape_08());
                // Layer: Circle 6
                shapes.Add(ContainerShape_09());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.600000024F, 0.600000024F), HoldThenStepEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(0.200000003F, 0.200000003F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 6
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.200000003F, 0.200000003F), _stepThenHoldEasingFunction);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, new Vector2(0.200000003F, 0.200000003F), _holdThenStepEasingFunction);
                // Frame 28.
                result.InsertKeyFrame(1F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 4
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 5
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 6
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_4()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            internal Circles_menu_1_AnimatedVisual_UAPv15(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(40F, 40F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 15);
            }
        }

        sealed class Circles_menu_1_AnimatedVisual_UAPv7 : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 11666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _colorBrush_AlmostSkyBlue_FF8BB7F0;
            CompositionColorBrush _colorBrush_AlmostSteelBlue_FF4E7AB5;
            CompositionPathGeometry _pathGeometry;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            ExpressionAnimation _rootProgress;
            ScalarKeyFrameAnimation _scalarAnimation_0p2_to_0p6;
            ScalarKeyFrameAnimation _scalarAnimation_0p6_to_0p2;
            ScalarKeyFrameAnimation _scalarAnimation_1_to_1_0;
            ScalarKeyFrameAnimation _scalarAnimation_1_to_1_1;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -3.5F));
                    builder.AddCubicBezier(new Vector2(-1.93299997F, -3.5F), new Vector2(-3.5F, -1.93299997F), new Vector2(-3.5F, 0F));
                    builder.AddCubicBezier(new Vector2(-3.5F, 1.93299997F), new Vector2(-1.93299997F, 3.5F), new Vector2(0F, 3.5F));
                    builder.AddCubicBezier(new Vector2(1.93299997F, 3.5F), new Vector2(3.5F, 1.93299997F), new Vector2(3.5F, 0F));
                    builder.AddCubicBezier(new Vector2(3.5F, -1.93299997F), new Vector2(1.93299997F, -3.5F), new Vector2(0F, -3.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostSkyBlue_FF8BB7F0()
            {
                return _colorBrush_AlmostSkyBlue_FF8BB7F0 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x8B, 0xB7, 0xF0));
            }

            CompositionColorBrush ColorBrush_AlmostSteelBlue_FF4E7AB5()
            {
                return _colorBrush_AlmostSteelBlue_FF4E7AB5 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x4E, 0x7A, 0xB5));
            }

            // Layer aggregator
            // Layer: Circle 1
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(ContainerShape_01());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_0(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 1
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(5F, 20F);
                // ShapeGroup: Group 2 Offset:<5, 20>
                result.Shapes.Add(SpriteShape_0());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_0(), RootProgress());
                return result;
            }

            // Layer aggregator
            // Layer: Circle 4
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_03());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_1(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 4
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(5F, 20F);
                // ShapeGroup: Group 2 Offset:<5, 20>
                result.Shapes.Add(SpriteShape_1());
                StartProgressBoundAnimation(result, "Scale.X", ScalarAnimation_0p2_to_0p6(), _rootProgress);
                StartProgressBoundAnimation(result, "Scale.Y", _scalarAnimation_0p2_to_0p6, _rootProgress);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 2
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(ContainerShape_05());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_2(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 2
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(20F, 20F);
                // ShapeGroup: Group 1 Offset:<20, 20>
                result.Shapes.Add(SpriteShape_2());
                StartProgressBoundAnimation(result, "Scale.X", ScalarAnimation_1_to_1_0(), _rootProgress);
                StartProgressBoundAnimation(result, "Scale.Y", _scalarAnimation_1_to_1_0, _rootProgress);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 5
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_07());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_3(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 5
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(20F, 20F);
                // ShapeGroup: Group 1 Offset:<20, 20>
                result.Shapes.Add(SpriteShape_3());
                StartProgressBoundAnimation(result, "Scale.X", ScalarAnimation_1_to_1_1(), _rootProgress);
                StartProgressBoundAnimation(result, "Scale.Y", _scalarAnimation_1_to_1_1, _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(35F, 20F);
                // ShapeGroup: Group 3 Offset:<35, 20>
                result.Shapes.Add(SpriteShape_4());
                StartProgressBoundAnimation(result, "Scale.X", ScalarAnimation_0p6_to_0p2(), _rootProgress);
                StartProgressBoundAnimation(result, "Scale.Y", _scalarAnimation_0p6_to_0p2, _rootProgress);
                return result;
            }

            // Layer aggregator
            // Layer: Circle 6
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                result.Shapes.Add(ContainerShape_10());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_4(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 6
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(35F, 20F);
                // ShapeGroup: Group 3 Offset:<35, 20>
                result.Shapes.Add(SpriteShape_5());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_1(), _rootProgress);
                return result;
            }

            CompositionPathGeometry PathGeometry()
            {
                return _pathGeometry = _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // - - Layer aggregator
            // - Layer: Circle 1
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<5, 20>
                var geometry = PathGeometry();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 5F, 20F), ColorBrush_AlmostSkyBlue_FF8BB7F0());;
                result.StrokeBrush = ColorBrush_AlmostSteelBlue_FF4E7AB5();
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 4
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<5, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 5F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 2
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<20, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 5
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<20, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<35, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 35F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 6
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<35, 20>
                var geometry = _pathGeometry;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 35F, 20F), _colorBrush_AlmostSkyBlue_FF8BB7F0);;
                result.StrokeBrush = _colorBrush_AlmostSteelBlue_FF4E7AB5;
                result.StrokeMiterLimit = 5F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.550000012F, 1F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.444000006F, 0F), new Vector2(0.833000004F, 0.833000004F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p2_to_0p6()
            {
                // Frame 0.
                var result = _scalarAnimation_0p2_to_0p6 = CreateScalarKeyFrameAnimation(0F, 0.200000003F, StepThenHoldEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, 0.200000003F, _holdThenStepEasingFunction);
                // Frame 19.
                result.InsertKeyFrame(0.678571403F, 1F, CubicBezierEasingFunction_1());
                // Frame 28.
                result.InsertKeyFrame(1F, 0.600000024F, CubicBezierEasingFunction_2());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0p6_to_0p2()
            {
                // Frame 0.
                var result = _scalarAnimation_0p6_to_0p2 = CreateScalarKeyFrameAnimation(0F, 0.600000024F, _holdThenStepEasingFunction);
                // Frame 8.
                result.InsertKeyFrame(0.285714298F, 1F, _cubicBezierEasingFunction_1);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, 0.200000003F, _cubicBezierEasingFunction_2);
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_1_to_1_0()
            {
                // Frame 0.
                var result = _scalarAnimation_1_to_1_0 = CreateScalarKeyFrameAnimation(0F, 1F, _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, 0.200000003F, _cubicBezierEasingFunction_2);
                // Frame 28.
                result.InsertKeyFrame(1F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.550000012F, 1F)));
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_1_to_1_1()
            {
                // Frame 0.
                var result = _scalarAnimation_1_to_1_1 = CreateScalarKeyFrameAnimation(0F, 1F, _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, 0.200000003F, _c.CreateCubicBezierEasingFunction(new Vector2(0.444000006F, 0F), new Vector2(0.833000004F, 1F)));
                // Frame 28.
                result.InsertKeyFrame(1F, 1F, _cubicBezierEasingFunction_1);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(40F, 40F);
                var shapes = result.Shapes;
                // Layer: Circle 1
                shapes.Add(ContainerShape_00());
                // Layer: Circle 4
                shapes.Add(ContainerShape_02());
                // Layer: Circle 2
                shapes.Add(ContainerShape_04());
                // Layer: Circle 5
                shapes.Add(ContainerShape_06());
                shapes.Add(ContainerShape_08());
                // Layer: Circle 6
                shapes.Add(ContainerShape_09());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.600000024F, 0.600000024F), HoldThenStepEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(0.200000003F, 0.200000003F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // - Layer: Circle 6
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.200000003F, 0.200000003F), _stepThenHoldEasingFunction);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, new Vector2(0.200000003F, 0.200000003F), _holdThenStepEasingFunction);
                // Frame 28.
                result.InsertKeyFrame(1F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 4
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 5.
                result.InsertKeyFrame(0.178571433F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 5
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Layer: Circle 6
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_4()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            internal Circles_menu_1_AnimatedVisual_UAPv7(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(40F, 40F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
